breast_cancer:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('HOST')}}"
      port: 5432
      user: "{{ env_var('DB_USERNAME')}}"
      password: "{{ env_var('DB_PASSWORD')}}"
      dbname: "{{ env_var('DB_NAME')}}"
      schema: dwh
