volumes:
  zoomcamp-data:
    driver: local
  superset-data:
  superset-init:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres_zoomcamp:
        condition: service_healthy

  postgres_zoomcamp:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - zoomcamp-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DB_PASSWORD} -U $${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    depends_on:
      postgres_zoomcamp:
        condition: service_started

  superset:
    image: apache/superset:2.1.0
    ports:
      - "8088:8088"
    env_file: .env
    volumes:
      - superset-data:/app/superset_home
      - ./superset_init:/app/superset_init 
    depends_on:
      - postgres_zoomcamp
    restart: unless-stopped
    command: ["sh", "-c", "superset fab create-admin --username $$SUPERSET_ADMIN_USERNAME --firstname $$SUPERSET_ADMIN_FIRST_NAME --lastname $$SUPERSET_ADMIN_LAST_NAME --email $$SUPERSET_ADMIN_EMAIL --password $$SUPERSET_ADMIN_PASSWORD && superset db upgrade && superset init && superset shell < /app/superset_init/create_db.py && superset import-dashboards -p /app/superset_init/dashboard.zip && /usr/bin/run-server.sh"]
