volumes:
  airflow-db-data:
  zoomcamp-data:
    driver: local
  superset-data:
  superset-init:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres_zoomcamp:
        condition: service_healthy

  postgres_zoomcamp:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - zoomcamp-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DB_PASSWORD} -U $${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "8085:80"
    depends_on:
      postgres_zoomcamp:
        condition: service_started

  superset:
    image: apache/superset:2.1.0
    ports:
      - "8088:8088"
    env_file: .env
    volumes:
      - superset-data:/app/superset_home
      - ./superset_init:/app/superset_init 
    depends_on:
      - postgres_zoomcamp
    restart: unless-stopped
    command: ["sh", "-c", "superset fab create-admin --username $$SUPERSET_ADMIN_USERNAME --firstname $$SUPERSET_ADMIN_FIRST_NAME --lastname $$SUPERSET_ADMIN_LAST_NAME --email $$SUPERSET_ADMIN_EMAIL --password $$SUPERSET_ADMIN_PASSWORD && superset db upgrade && superset init && superset shell < /app/superset_init/create_db.py && superset import-dashboards -p /app/superset_init/dashboard.zip && /usr/bin/run-server.sh"]

  postgres_airflow: 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: airflow
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - PYTHONPATH=/opt/airflow:/opt/airflow/dags:/app
    depends_on:
      postgres_airflow:
        condition: service_healthy
    command: >
      bash -c "
      airflow db init && sleep 5 &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: airflow
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - PYTHONPATH=/opt/airflow:/opt/airflow/dags
      - PATH=/home/airflow/.local/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    restart: unless-stopped
    command: webserver
    
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: airflow
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      - PYTHONPATH=/opt/airflow:/opt/airflow/dags
      - PATH=/home/airflow/.local/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init
    restart: unless-stopped
    command: scheduler
